# Runs on the build host, including when the native executables target Android.
if(NOT DEFINED SHADER_DIR)
  message(FATAL_ERROR "SHADER_DIR is required")
endif()
set(SHADERS fp32_compute fp32_compute_12 fp32_compute_16
  fp16_native fp16_native_12 fp16_native_16
  fp16_emulated fp16_emulated_12 fp16_emulated_16
  int32_compute mixed_compute memory_bandwidth)
foreach(NAME IN LISTS SHADERS)
  file(READ "${SHADER_DIR}/${NAME}.comp" SOURCE)
  if(NOT SOURCE MATCHES "local_size_x = 64")
    message(FATAL_ERROR "${NAME}: host workgroup size no longer matches shader")
  endif()
  if(NAME STREQUAL "memory_bandwidth")
    if(NOT SOURCE MATCHES "item < 16u")
      message(FATAL_ERROR "${NAME}: memory byte count no longer matches shader")
    endif()
    continue()
  endif()
  if(NOT SOURCE MATCHES "output_buffer.values\\[parameters.output_offset \\+ index\\]")
    message(FATAL_ERROR "${NAME}: output ring offset is not applied")
  endif()
  if(NOT SOURCE MATCHES "iteration < 64")
    message(FATAL_ERROR "${NAME}: iteration count no longer matches host")
  endif()
  if(NAME MATCHES "^fp")
    set(EXPECTED 8)
    if(NAME MATCHES "_12$")
      set(EXPECTED 12)
    elseif(NAME MATCHES "_16$")
      set(EXPECTED 16)
    endif()
    string(REGEX MATCHALL "a[0-9]+ = fma\\(" FMAS "${SOURCE}")
    list(LENGTH FMAS ACTUAL)
    if(NOT ACTUAL EQUAL EXPECTED)
      message(FATAL_ERROR "${NAME}: expected ${EXPECTED} vector FMAs, found ${ACTUAL}")
    endif()
  endif()
endforeach()
message(STATUS "All 12 shader source contracts passed")
